# Copia de los campos del mensaje estándar sensor_msgs/Imu
geometry_msgs/Quaternion orientation
float64[9] orientation_covariance
geometry_msgs/Vector3 angular_velocity
float64[9] angular_velocity_covariance
geometry_msgs/Vector3 linear_acceleration
float64[9] linear_acceleration_covariance

# Campos adicionales
float64 temperature
geometry_msgs/Vector3 magnetic_field
geometry_msgs/Quaternion quaternion
geometry_msgs/Vector3 gravity
